n = input('Digite algo: ')
print('É alfanumerico?')
print(n.isalnum())
print('É alfabetico?')
print(n.isalpha())
print('Você escreveu algo? ')
print(n.isascii())
print('É um numero?')
print(n.isnumeric())
print('Estar em letra maiuscula')
print(n.isupper())
print('Esta em letra minuscula')
print(n.islower())
